<?php foreach ($this->content as $content):?>
<div class="hero-unit">
    <p><?php echo $content->getAttribute('id');echo $content->nodeValue;?></p>
    <?php echo get_class($content);?>
    <?php print_r($content->getElementsByTagName('span'));?>
    <?php //print_r($content->firstChild->firstChild->lastChild)?>
    <?php 
   // foreach ($content->attributes as $attr => $v){
        //echo $attr."=".$v->textContent."<br/>";
    //}
    ?>
</div>
<?php endforeach;?>
